// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Coba struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type NewCobaInput struct {
	Name string `json:"name"`
}

type Query struct {
}

type UpdateCobaInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
